### PR TITLE
Releasing v1.5.0

### PR DESCRIPTION
**Pull request by arunkannawadi**

### CODE REVIEW

**Comment by arunkannawadi** [comment]
There are some duplicate commits arising in attempting to adjust for commits that were directly committed to `main`. We should avoid this in the future and edit `develop` and raise a PR to `main`.

**Comment by ipeirotis** [comment]
Do you think it is possible to setup a protection rule that we can only commit to `main` from `develop`?

**Comment by arunkannawadi** [comment]
Done. For `main`, the admins can't overrule the branch protection rules but they can for `develop`. This is sufficient to prevent these two beaches from diverging. Now as a result, I need this PR to be approved :-D

**Comment by arunkannawadi** [comment]
Duplicate commits removed by force-pushing directly into `develop` (flouting the branch protection rules for now)

**Comment by arunkannawadi** [comment]
`pip install scholarly` is broken in v1.5.0-alpha and that's not captured in our unit tests. So I'll merge it by tonight before we hear any complaints.

**Review by ipeirotis — APPROVED** [review]

**Pull request merged**
