### PR TITLE
fix: set minimum free-proxy version

### PR DESCRIPTION
**Pull request by ltalirz**
scholarly requires free-proxy >= 1.1.0, see
```
  File "/.../scholarly/_proxy_generator.py", line 509, in _fp_coroutine
    all_proxies = freeproxy.get_proxy_list(repeat=False)  # free-proxy >= 1.1.0
TypeError: get_proxy_list() got an unexpected keyword argument 'repeat'
```

Fixes #Enter the associated issue number.

### Description
Describe your addition briefly to help the reviewers understand your contribution.

## Checklist

- [x] Check that the base branch is set to `develop` and **not** `main`.
- [x] Ensure that the documentation will be consistent with the code upon merging.
- [ ] Add a line or a few lines that check the new features added.
- [ ] Ensure that unit tests pass.
        If you don't have a premium proxy, some of the tests will be skipped.
        The tests that are run should pass without raising
        `MaxTriesExceededException` or other exceptions.

### CODE REVIEW

**Comment by arunkannawadi** [comment]
Did you get an error there actually? This is within a `try`/`except` block, so it should be insensitive to whether we are using `fp` before or after the breaking change.

**Comment by ltalirz** [comment]
You are right - this excerpt I copied was part of the stack trace (and I incorrectly assumed it was the source of the error), but the actual error was:
```
  File "/.../fp/fp.py", line 24, in get_proxy_list
    proxies = [f'{tr_elements[i][0].text_content()}:{tr_elements[i][1].text_content()}' for i in
  File "/.../fp/fp.py", line 24, in <listcomp>
    proxies = [f'{tr_elements[i][0].text_content()}:{tr_elements[i][1].text_content()}' for i in
IndexError: list index out of range
```

This was with free-proxy 1.0.2. Upgrading to 1.1.0 fixed the issue

**Comment by arunkannawadi** [comment]
I hadn't seen this error before. Perhaps it's best to require this. I'd leave the `try/except` block as it is for now.

**Comment by arunkannawadi** [comment]
Thanks for the two PRs.

**Pull request merged**
