### PR TITLE
moved SearchScholarIterator to separate file to improve readability

### PR DESCRIPTION
**Pull request by dlebedinsky**
Fixes #Enter the associated issue number.

### Description
Describe your addition briefly to help the reviewers understand your contribution.

## Checklist

- [x] Check that the base branch is set to `develop` and **not** `main`.
- [x] Ensure that the documentation will be consistent with the code upon merging.
- [x] Add a line or a few lines that check the new features added.
- [x] Ensure that unit tests pass.
        If you don't have a premium proxy, some of the tests will be skipped.
        The tests that are run should pass without raising
        `MaxTriesExceededException` or other exceptions.

### CODE REVIEW

**Comment by dlebedinsky** [comment]
Hello, this is my first contribution. I hope to make more in the future.

**Comment by arunkannawadi** [comment]
@dlebedinsky - any reason why you closed this PR again?

**Comment by dlebedinsky** [comment]
> @dlebedinsky - any reason why you closed this PR again?

It resulted in a circular import error

**Comment by arunkannawadi** [comment]
Right, you were calling `publication_parser` from `_search_scholar_iterator` and vice versa, that would result in that error. You could avoid it by moving the import just before it is needed, but I am not sure that it's a net win.

**Pull request closed without merging**
