### PR TITLE
Maintenance v1.5 patch2

### PR DESCRIPTION
**Pull request by arunkannawadi**
Tagging this as a pre-release so that @silvavn can get the DOI and tag the updated one as v1.5

### CODE REVIEW

**Comment by arunkannawadi** [comment]
I will (and be able to) rebase it after I get an approval on this PR

**Review by silvavn — APPROVED** [review]

**Comment by arunkannawadi** [comment]
Can't work with protected branches. @ipeirotis please fix this

image

**Comment by ipeirotis** [comment]
Again, the problem is that the branch name "maintenance" matches the regex for the protection of the branch "main". The intention of the regex is just to protect "develop" and "main" but the supported language for regexes for protection rules is rather limited when I tried. If you have a better way please go ahead and change the regex for the protection rule.

**Comment by arunkannawadi** [comment]
I created two identical sets of rules, one for `main` and another one for `develop`. These look for exact matches so it won't mark any other branch as protected.

**Pull request merged**
